structural:
  _target_: src.datasets.TripletStructuralDataset
  data_path: ${connected_dir}/data
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  anchor_column_name: ${anchor_column_name}
  positive_column_name: ${positive_column_name}
  negative_column_name: ${negative_column_name}
